version: '3'

services:
    agent:
      restart: always
      build: ./agent
      environment:
        - DESTINATION_HOST=${DESTINATION_HOST}
        - EXTERNAL_IP=${EXTERNAL_IP}
    management:
      restart: always
      build: ./management
      volumes:
        - /data:/data
      ports:
        - "8081:80"